import { DOTSX } from '@/lib/constants';
import type { Domain } from '@/types';

export const debianDomain: Domain = {
  name: 'debian',
  type: 'os',
  availableOs: ['debian'],
  packageManagers: {
    apt: {
      configPath: DOTSX.OS.DEBIAN.APT,
      install: 'sudo apt install -y %s',
      remove: 'sudo apt remove -y %s',
      status: 'dpkg -l | grep "^ii" | grep -w " %s "',
      defaultContent: `# APT packages
# Generated by dotsx
# Add package names, one per line
# Lines starting with # are ignored
`,
    },
    snap: {
      configPath: DOTSX.OS.DEBIAN.SNAP,
      install: 'sudo snap install %s',
      remove: 'sudo snap remove %s',
      status: 'snap list | grep -w "%s "',
      defaultContent: `# Snap packages
# Generated by dotsx
# Add package names, one per line
# Lines starting with # are ignored
`,
    },
  },
};
